backend:
  name: git-gateway
  branch: main

local_backend: true

locale: de

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [de, en]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: de

  # Optional, defaults to true
  # When true, new entries will be created with all locales pre-filled with the value of the default locale.
  # When false, new entries will be created with no values.
  default_missing_locale_values: true


media_folder: static/
public_folder: /

collections:
  - name: "seiten"
    label: "Seiten"
    format: "frontmatter"
    extension: 'md'
    folder: "content/seiten"
    create: true
    sortable_fields: ["title"]
    slug: "{{fields.siteTitle}}"
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Seitentitel", name: "siteTitle", widget: "string", i18n: true }
      - { label: "Menüreihenfolge", name: "menuOrder", widget: "number", i18n: true }
      - { label: "im Menü verstecken", name: "hideInMenu", widget: "boolean", default: false, required: false, i18n: true }
      - label: "Landing Slider"
        name: "landingSlider"
        widget: "list"
        i18n: true
        fields:
          - {label: Titel, name: landingTitle, widget: string }
          - label: Titel Position
            name: landingTitlePosition
            widget: select
            options:
              - { label: "Links Oben", value: "top-left" }
              - { label: "Rechts Oben", value: "top-right" }
              - { label: "Mitte", value: "center" }
              - { label: "Links Unten", value: "bottom-left" }
              - { label: "Rechts Unten", value: "bottom-right" }
          - label: Bild/er
            name: landingImage
            widget: image
            required: false
            i18n: true
          - label: "Verknüpfte Produkte"
            name: "landingProducts"
            widget: "relation"
            collection: "produkte"
            multiple: true
            required: false
            value_field: "{{slug}}"
            search_fields: ["productTitle"]
            display_fields: ["productTitle"]
            i18n: true

      - label: "Seiteninhalt"
        name: "contentblock"
        widget: "list"
        i18n: true
        fields:
          - {label: "Überschrift", name: "contentTitle", widget: "string", required: false, i18n: true }
          - {label: "Textinhalt", name: "contentText", widget: "markdown", required: false, i18n: true }
          
          - label: "Blöcke"
            name: "blocks"
            widget: "list"
            i18n: true
            required: false
            fields:
              - {label: "Kategorie", name: "blockCategory", widget: "string", required: false, i18n: true }
              - {label: "Überschrift", name: "blockTitle", widget: "string", required: false, i18n: true }
              - label: "Bild/er"
                name: "blockImage"
                widget: "image"
                required: false
                i18n: true
              - label: "Link"
                name: "blockLink"
                widget: "relation"
                required: false
                i18n: true 
                collection: "seiten"
                value_field: "title"
                search_fields: ["title"]
                display_fields: ["title"]

          - label: "Product Vorschau"
            name: "productPreview"
            widget: "object"
            i18n: true
            fields:
              - label: "Produkt"
                name: "product"
                widget: "relation"
                required: false
                i18n: true 
                collection: "produkte"
                value_field: "{{slug}}"
                search_fields: ["productTitle"]
                display_fields: ["productTitle"]
              - label: "Bild/er"
                name: "productImage"
                widget: "image"
                required: false
                i18n: true
              - label: "Titel"
                name: "productTitle"
                widget: "string"
                required: false
                i18n: true
              - label: "Beschreibung"
                name: "productDescription"
                widget: "markdown"
                required: false
                i18n: true
              - label: "Zitat"
                name: "productQuote"
                widget: "string"
                required: false
                i18n: true

          - label: "Karten"
            name: "cards"
            widget: "list"
            i18n: true
            fields:
              - {label: "Überschrift", name: "cardTitle", widget: "string", required: false, i18n: true }
              - {label: "Textinhalt", name: "cardText", widget: "markdown", required: false, i18n: true }
              - label: "Bild/er"
                name: "cardImage"
                widget: "image"
                required: false
                i18n: true
              - label: "Link"
                name: "cardLink"
                widget: "relation"
                required: false
                i18n: true 
                collection: "seiten"
                value_field: "title"
                search_fields: ["title"]
                display_fields: ["title"]

          - label: "Aktuelle News"
            name: "news"
            widget: "boolean"
            i18n: true
            default: false

  - name: "kompetenzen"
    label: "Kompetenzen"
    format: "frontmatter"
    extension: 'md'
    folder: "content/kompetenzen"
    create: true
    sortable_fields: ["title"]
    slug: "{{fields.competenceName}}"
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Kompetzenzname", name: "competenceName", widget: "string", i18n: true, hint: "Bspw: Spritzguss, Insertteile ..." }
      - { label: "Kompezenzposition", name: "competencePosition", widget: "number", i18n: true}
      - { label: "Kompetenztitel", name: "competenceTitle", widget: "string", i18n: true}
      - { label: "Kompetenzbeschreibung", name: "competenceDescription", widget: "markdown", i18n: true }
      - { label: "Kompetenzbild", name: "competenceImage", widget: "image", required: false, i18n: true }
      - label: "Button Text"
        name: "competenceButtonText"
        widget: "string"
        i18n: true
        required: false
      - label: "Button Link"
        name: "competenceButtonLink"
        widget: "relation"
        required: false
        i18n: true 
        collection: "seiten"
        value_field: "{{slug}}"
        search_fields: ["siteTitle"]
        display_fields: ["siteTitle"]
      - label: "Button Externer Link"
        name: "competenceButtonExternalLink"
        widget: "string"
        required: false
        i18n: true
      - label: "Button Datei"
        name: "competenceButtonFile"
        widget: "file"
        required: false
        i18n: true
      - label: "Bild oder Button"
        name: "competenceSideInfo"
        widget: "list"
        required: false
        i18n: true
        fields:
          - label: "Bild"
            name: "image"
            widget: "image"
            required: false
            i18n: true
          - label: "Button Text"
            name: "buttonText"
            widget: "string"
            i18n: true
            required: false
          - label: "Button Link"
            name: "buttonLink"
            widget: "relation"
            required: false
            i18n: true 
            collection: "seiten"
            value_field: "{{slug}}"
            search_fields: ["siteTitle"]
            display_fields: ["siteTitle"]
          - label: "Button Externer Link"
            name: "buttonExternalLink"
            widget: "string"
            required: false
            i18n: true
          - label: "Button Datei Download"
            name: "buttonFileDownload"
            widget: "file"
            required: false
            i18n: true
          
  - name: "qualitaeten"
    label: "Qualitäten"
    format: "frontmatter"
    extension: 'md'
    folder: "content/qualitaeten"
    create: true
    sortable_fields: ["title"]
    slug: "{{fields.qualityName}}"
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Qualitätsname", name: "qualityName", widget: "string", i18n: true, hint: "Bspw: ISO 9001:2015, ISO 14001:2015 ..." }
      - { label: "Qualitätstitel", name: "qualityTitle", widget: "string", i18n: true}
      - label: "Inhalt"
        name: "content"
        widget: "list"
        i18n: true
        fields:
          - { label: "Qualitätstext", name: "qualitytext", widget: "markdown", i18n: true }
          - label: "Bild/er"
            name: "qualityImage"
            widget: "image"
            required: false
            i18n: true
          - label: "Button Text"
            name: "qualityButtonText"
            widget: "string"
            i18n: true
            required: false
          - label: "Button"
            name: "qualityButton"
            widget: "relation"
            required: false
            i18n: true 
            collection: "seiten"
            value_field: "{{slug}}"
            search_fields: ["siteTitle"]
            display_fields: ["siteTitle"]
          - label: "Button Externer Link"
            name: "qualityButtonExternalLink"
            widget: "string"
            required: false
            i18n: true

  - name: "produkte"
    label: "Produkte"
    format: "frontmatter"
    extension: 'md'
    folder: "content/produkte"
    create: true
    sortable_fields: ["title"]
    slug: "{{fields.productTitle}}"
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Produktname", name: "productTitle", widget: "string", i18n: true }
      - { label: "Produktbeschreibung", name: "productDescription", widget: "markdown", i18n: true }
      - {label: "Produktbild", name: "productImage", widget: "image", required: false, i18n: true }
      - label: "Produktkategorien"
        name: "productCategories"
        widget: "relation"
        collection: "kategorien"
        multiple: true
        value_field: "productCategoryTitle"
        search_fields: ["productCategoryTitle"]
        display_fields: ["productCategoryTitle"]
        required: false
        i18n: true
      - label: "Produktmerkmale"
        name: "productFeatures"
        widget: "list"
        i18n: true
        required: false
        fields:
          - {label: "Überschrift", name: "featureTitle", widget: "string", required: false, i18n: true }
          - {label: "Textinhalt", name: "featureText", widget: "string", required: false, i18n: true }
      - label: "Bildgallerie"
        name: "productGallery"
        widget: "list"
        i18n: true
        required: false
        fields:
          - label: "Bild/er"
            name: "productGalleryImage"
            widget: "image"
            required: false
            i18n: true
          - {label: "Bildunterschrift", name: "productGalleryCaption", widget: "string", required: false, i18n: true }

  - name: "kategorien"
    label: "Produktkategorien"
    format: "frontmatter"
    extension: 'md'
    folder: "content/kategorien"
    create: true
    slug: "{{fields.productCategoryTitle}}"
    sortable_fields: ["productCategoryTitle"]
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Kategoriename", name: "productCategoryTitle", widget: "string", i18n: true }
      - { label: "Kategoriebeschreibung", name: "productCategoryDescription", widget: "markdown", i18n: true, required: false }

  - name: "blog"
    label: "Blog & News"
    format: "frontmatter"
    extension: 'md'
    folder: "content/blog"
    slug: "{{fields.title}}"
    create: true
    sortable_fields: ["title"]
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string", i18n: true }
      - { label: "Beschreibung", name: "description", widget: "markdown", i18n: true }
      - { label: "Datum", name: "date", widget: "datetime", format: "YYYY-MM-DD", i18n: true }
      - { label: "Autor", name: "author", widget: "string", i18n: true }
      - { label: "Bild", name: "image", widget: "image", required: false, i18n: true }
      - { label: "Inhalt", name: "body", widget: "markdown", i18n: true }
      - label: "Kategorien"
        name: "categories"
        widget: "relation"
        collection: "blogkategorien"
        multiple: true
        value_field: "title"
        search_fields: ["title"]
        display_fields: ["title"]
        i18n: true
      
  - name: "blogkategorien"
    label: "Blogkategorien"
    format: "frontmatter"
    extension: 'md'
    folder: "content/blogkategorien"
    create: true
    sortable_fields: ["categoryTitle"]
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Kategoriename", name: "categoryTitle", widget: "string", i18n: true }
      - { label: "Kategoriebeschreibung", name: "categoryDescription", widget: "markdown", i18n: true }


  - name: "testseiten"
    label: "Testseiten"
    format: "frontmatter"
    extension: 'md'
    folder: "content/testSeiten"
    create: true
    sortable_fields: ["title"]
    slug: "{{fields.siteTitle}}"
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Seitentitel", name: "siteTitle", widget: "string", i18n: true }
      - { label: "Menüreihenfolge", name: "menuOrder", widget: "number", i18n: true }
      - { label: "im Menü verstecken", name: "hideInMenu", widget: "boolean", default: false, required: false, i18n: true }
      - label: "Landing Slider"
        name: "landingSlider"
        widget: "list"
        i18n: true
        types:
          - label: "Slider"
            name: "slider"
            widget: "object"
            summary: "{{fields.sliderTitle}}"
            fields:
              - {label: Titel, name: landingTitle, widget: string }
              - label: Titel Position
                name: landingTitlePosition
                widget: select
                options:
                  - { label: "Links Oben", value: "top-left" }
                  - { label: "Rechts Oben", value: "top-right" }
                  - { label: "Mitte", value: "center" }
                  - { label: "Links Unten", value: "bottom-left" }
                  - { label: "Rechts Unten", value: "bottom-right" }
              - label: Bild/er
                name: landingImage
                widget: image
                required: false
                i18n: true
              - label: "Verknüpfte Produkte"
                name: "landingProducts"
                widget: "relation"
                collection: "produkte"
                multiple: true
                required: false
                value_field: "{{slug}}"
                search_fields: ["productTitle"]
                display_fields: ["productTitle"]
                i18n: true